name: Create GitHub Release

on:
  push:
    tags:
      - 'v*.*.*' # vで始まるタグがプッシュされたときに実行

jobs:
  # draft_release ジョブは削除

  build-and-release:
    # needs: draft_release は削除
    runs-on: ubuntu-latest # 実行環境
    permissions:
      contents: write # リリース作成・アセットアップロードのために必要

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # オプション: チェンジログ生成のために全履歴を取得
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.x

      # オプション: Denoの依存関係キャッシュ (ビルド高速化のため)
      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Build single HTML file
        run: deno task release:build

      # ★ 追加: git-cliff をインストール
      - name: Install git-cliff
        run: |
          curl -Ls https://github.com/orhun/git-cliff/releases/latest/download/git-cliff-x86_64-unknown-linux-gnu.tar.gz | tar xz
          echo "$PWD" >> $GITHUB_PATH # Add current dir to PATH to find git-cliff

      # ★ 追加: git-cliff でリリースノートを生成
      - name: Generate Changelog
        id: generate_changelog
        run: |
          git-cliff --output RELEASE_NOTES.md ${{ github.ref_name }}
          echo "Generated RELEASE_NOTES.md"

      # ★ 変更点: gh release create を使用してリリース作成とアセットアップロード
      - name: Create GitHub Release and Upload Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes-file RELEASE_NOTES.md \
            ./dist/tanshu3.html # アップロードするアセット

          echo "Release ${{ github.ref_name }} created and tanshu3.html artifact uploaded."
