name: Create GitHub Release

on:
  push:
    tags:
      - 'v*.*.*' # vで始まるタグがプッシュされたときに実行

jobs:
  # draft_release ジョブは削除

  build-and-release:
    # needs: draft_release は削除
    runs-on: ubuntu-latest # 実行環境
    permissions:
      contents: write # リリース作成・アセットアップロードのために必要

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # オプション: チェンジログ生成のために全履歴を取得
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.x

      # オプション: Denoの依存関係キャッシュ (ビルド高速化のため)
      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Build single HTML file
        run: deno task release:build

      # ★ 変更点: orhun/git-cliff-action を使用してリリースノートを生成
      - name: Generate Changelog with git-cliff
        uses: orhun/git-cliff-action@v3
        id: git-cliff # ステップIDを設定 (オプション)
        with:
          config: cliff.toml # 設定ファイルを指定
          args: -o RELEASE_NOTES.md --tag ${{ github.ref_name }} # 出力ファイルと対象タグを指定
        env:
          # OUTPUT: RELEASE_NOTES.md # with.args で出力ファイルを指定するため不要な場合が多い
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # リポジトリ情報取得に必要

      # ★ 変更点なし: 生成された RELEASE_NOTES.md を使用
      - name: Create GitHub Release and Upload Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes-file RELEASE_NOTES.md \
            ./dist/tanshu3.html # アップロードするアセット

          echo "Release ${{ github.ref_name }} created and tanshu3.html artifact uploaded."
