name: Create GitHub Release

on:
  push:
    tags:
      - 'v*.*.*' # vで始まるタグがプッシュされたときに実行

jobs:
  draft_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to create release drafts
      pull-requests: read # to read pull request information
    steps:
      - name: Draft release notes
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml # Use our custom config
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-release:
    needs: draft_release # Wait for the draft to be created
    runs-on: ubuntu-latest # 実行環境
    permissions:
      contents: write # リリース編集・アセットアップロードのために必要

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.x

      # オプション: Denoの依存関係キャッシュ (ビルド高速化のため)
      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Build single HTML file
        run: deno task release:build

      - name: Edit GitHub Release and Upload Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 自動的に提供されるトークン
        run: |
          gh release edit ${{ github.ref_name }} --draft=false --add-asset ./dist/tanshu3.html
          echo "Release ${{ github.ref_name }} published with tanshu3.html artifact."
